### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by cyatarow** [Aloereed/ultimatevocalremovergui-directml#1]
I cannot run this program due to this error:

```
C:\AppsForSSD\ultimatevocalremovergui-directml>Python UVR.py
Traceback (most recent call last):
  File "C:\AppsForSSD\ultimatevocalremovergui-directml\UVR.py", line 26, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

My environment:
- Windows 11 Pro 22H2
- Radeon RX 5500 XT 8GB

**Comment by Aloereed** [comment]
tkinter should be installed with python. You can install the miniconda environment, or check that your python installation is checked this.
![image](https://user-images.githubusercontent.com/58137529/220221689-29662288-30fe-489c-aea7-a9125e05f6de.png)

**Comment by cyatarow** [comment]
Thank you.
I had installed Python without checking those options.
After reinstalling them, UVR works successfully.
