### ISSUE TITLE
No more update?

### ISSUE THREAD

**Issue by cyatarow** [Aloereed/ultimatevocalremovergui-directml#10]
@Aloereed 
It seems like you haven't been active in this repo for a long time. Did you stop developing it?
[The source repo is now v5.6 and supports MDX23C.](https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.6) I can't wait to use MDX23C with Intel Arc.

**Comment by Aloereed** [comment]
v5.6 will be released soon.

**Comment by Aloereed** [comment]
Intel and AMD GPUs are officially supported.
